### ISSUE TITLE
InvoiceNinja app not launching from Ubuntu start menu

### ISSUE THREAD

**Issue by CodeShakingSheep** [flathub/com.invoiceninja.InvoiceNinja#16]
Instead of launching the app when clicking on the app from start menu, nothing happens. So, I debugged it and ran this command (taken from Exec in `var/lib/flatpak/exports/share/applications/com.invoiceninja.InvoiceNinja.desktop`) in terminal.
```
/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=invoiceninja_client com.invoiceninja.InvoiceNinja
``` 

An error message gets printed and nothing else happens.

```
bwrap: execvp invoiceninja_client: No such file or directory
```

The command works without the `--command` argument.
```
/usr/bin/flatpak run --branch=stable --arch=x86_64 com.invoiceninja.InvoiceNinja
```

After analyzing I changed the Exec in `var/lib/flatpak/exports/share/applications/com.invoiceninja.InvoiceNinja.desktop` to the working command and afterwards the app launched fine. However, the problem is that with every app update the `.desktop` file gets overridden which leads to the faulty Exec being present again and the app not launching from start menu.

So, can you kindly update the Exec in `.desktop` file to fix it long term?

**Comment by hillelcoren** [comment]
Hi,

Sorry for the delayed response, thanks for reporting this!

Does this command work?

`/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=invoiceninja com.invoiceninja.InvoiceNinja`

I believe this is the source file: 

https://github.com/invoiceninja/admin-portal/blob/master/flatpak/com.invoiceninja.InvoiceNinja.desktop

**Comment by CodeShakingSheep** [comment]
Thanks for your reply @hillelcoren . Yes, the command you provided works.

**Comment by hillelcoren** [comment]
Thanks for the info, I'll update the app to match

**Comment by ashermiddleton** [comment]
Also had the same problem on Fedora 39 KDE spin. Until the [new flatpak build passes](https://github.com/flathub/com.invoiceninja.InvoiceNinja/pull/15), I've changed the .desktop to match the changes from invoiceninja/admin-portal@2219d26:
```
#/var/lib/flatpak/app/com.invoiceninja.InvoiceNinja/x86_64/stable/active/export/share/applications/com.invoiceninja.InvoiceNinja.desktop

[Desktop Entry]
Version=1.0
Type=Application
Name=Invoice Ninja
Comment=Create invoices, accept payments, track expenses & time tasks
Categories=Office;
Icon=com.invoiceninja.InvoiceNinja
Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=invoiceninja com.invoiceninja.InvoiceNinja
Terminal=false
StartupWMClass=invoiceninja
X-Flatpak=com.invoiceninja.InvoiceNinja
```

After a logging out and in the app opens and works without any dramas now, cheers.

**Comment by hillelcoren** [comment]
Thanks for the info, this should hopefully mean that the next version will work...
